name: graviitee
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.7.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  draggable_home: ^1.0.2
  flip_card: ^0.6.0
  carousel_slider: ^4.0.0
  country_icons: ^2.0.2
  flutter_map: ^0.14.0
  url_launcher: ^6.0.2
  ola_like_country_picker: ^0.1.2
  expandable: ^5.0.1
  sqflite: 2.0.1
  path_provider: ^2.0.8
  favorite_button: ^0.0.4
  dio: ^4.0.4
  fade_shimmer: ^2.0.1
  shared_preferences:
  google_fonts: ^2.1.0
  connectivity_wrapper: ^1.0.6
  pull_to_refresh: ^2.0.0
  introduction_screen: ^2.1.0
  flutter_signin_button: 1.1.0
  animated_background: ^2.0.0
  intl_phone_field: ^2.1.0
  google_sign_in: ^5.2.1
  gallery_saver:
  http: ^0.13.0
  video_player:
  form_field_validator:
  get: 4.5.1
  flutter: 
    sdk: flutter
  firebase_core: ^1.10.6
  firebase_auth: ^3.3.4
  flutter_facebook_login: ^3.0.0
  uni_links: ^0.5.1
  flutter_twitter_login: ^1.1.0
  github_login: ^0.0.2
  progress_indicators: ^1.0.0
  get_storage: ^2.0.3
  flutter_smart_dialog: ^3.1.0
  skeleton_loader: ^2.0.0+4
  like_button: ^2.0.4
  flutter_share: ^2.0.0
  flutter_onboarding_screen: 2.0.2
  camera: 0.5.7+4
  tflite: 1.0.4
  pinch_zoom: ^1.0.0
  flutter_font_picker: ^0.3.3
  flutter_swipe_detector: ^2.0.0
  expandable_bottom_sheet: ^1.1.1+1
  flutter_widget_from_html_core: ^0.8.5+1
dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/
    - assets/short/
    - assets/ssd_mobilenet.tflite
    - assets/ssd_mobilenet.txt
    - assets/aa.png
